### ISSUE TITLE
删除item1后，刷新页面，新的Item1保留了删除状态

### ISSUE THREAD

**Issue by wushiqiwu** [mjl0602/left-scroll-actions#1]
1.点击删除调用删除接口
2.调用刷新接口，刷新最新数据
3.新的List里，第一个item1，保留了删除状态

**Comment by wushiqiwu** [comment]
<img width="919" alt="image" src="https://user-images.githubusercontent.com/15612176/62180783-c80e9f80-b383-11e9-99c1-50f79edc5de3.png">

**Comment by OldJii** [comment]
@wushiqiwu 老哥，“新的List保留状态“这个问题是怎么解决的？

**Comment by mjl0602** [comment]
兄弟，提供key即可 @wushiqiwu @OldJii

**Comment by mjl0602** [comment]
在最新的Demo中我增加了对应例子🌰
