### ISSUE TITLE
你好！在你的项目中，我看不到任何版声明

### ISSUE THREAD

**Issue by bensontung** [mjl0602/left-scroll-actions#11]
在你的项目中，我看不到任何版声明，请问我们的项目中，能使用你的代码吗？如果可以，我可以使用任何开源许可吗？

**Comment by mjl0602** [comment]
你好，可以任意使用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Benson Tung"<notifications@github.com&gt;; 
发送时间: 2020年11月5日(星期四) 下午4:00
收件人: "fluttercandies/left-scroll-actions"<left-scroll-actions@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [fluttercandies/left-scroll-actions] 你好！在你的项目中，我看不到任何版声明 (#11)





 
在你的项目中，我看不到任何版声明，请问我们的项目中，能使用你的代码吗？如果可以，我可以使用任何开源许可吗？

**Comment by bensontung** [comment]
好，谢谢!
