### ISSUE TITLE
滑动选项溢出容器

### ISSUE THREAD

**Issue by naaaacI-Y** [mjl0602/left-scroll-actions#12]
你好，想请教下，最外层的容器添加padding，容器里面用listview包裹滑动项，向左滑动时滑动项会超出，是以视口为参照的，想问下有没有什么解决办法，谢谢。

>
![WX20201108-185146](https://user-images.githubusercontent.com/42194987/98463042-7ba34800-21f3-11eb-9c25-8fd499179a4a.png)

**Comment by mjl0602** [comment]
使用ClipRect或者ClipRRect即可。

**Comment by mjl0602** [comment]
另外，这是一个重复issue，提issue前请查看之前的旧issue。
