### ISSUE TITLE
support for flutter 3

### ISSUE THREAD

**Issue by inkl** [mjl0602/left-scroll-actions#16]
any plan to upgrade to flutter 3?

<img width="1152" alt="Screenshot 2022-06-07 at 10 52 57 AM" src="https://user-images.githubusercontent.com/5955069/172285698-9ab31fc6-8648-4fae-b233-24986d1339b0.png">

here is my dart version.

[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 3.0.1 at /Users/gln/Documents/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

**Comment by mjl0602** [comment]
See version 2.1.1.
