### ISSUE TITLE
左滑，操作按钮也行左边滑出现

### ISSUE THREAD

**Issue by kl2426** [mjl0602/left-scroll-actions#2]
能不能，左滑，操作按钮也行左边滑出现。
现在的直接在下层挡住的不好看。

**Comment by mjl0602** [comment]
我在demo中有自定义透明度变化的效果，你也可以自定义其他联动效果，是可以实现的。

**Comment by mjl0602** [comment]
在1.4.0版本我提供了CupertinoLeftScroll类，由LeftScroll替换成CupertinoLeftScroll即可获取你描述的效果。
