### ISSUE TITLE
IOS上屏蔽了右划返回上页的事件

### ISSUE THREAD

**Issue by what2003** [mjl0602/left-scroll-actions#3]
你好，感谢开发这样好用的插件，但IOS上屏蔽了右划返回上页的事件，请问可以同时保留吗，还是必然会屏蔽呢？谢谢！

**Comment by mjl0602** [comment]
您好，这个功能是这样的：安卓在展开的情况下点击返回案件，组件会阻止页面弹出，然后触发一个关闭动画。

所以在新版本中，我增加了一个参数，来对该行为进行控制，在关闭该功能时，不会覆盖页面手势。

扩展资料：[flutter 页面右滑返回失效研究](https://blog.csdn.net/langzxz/article/details/82986601)

在这篇文章中，阅读`route.hasScopedWillPopCallback`相关信息即可。
