### ISSUE TITLE
自行恢复原样

### ISSUE THREAD

**Issue by opennflower** [mjl0602/left-scroll-actions#4]
点击其他地方。已经左侧滑动自行恢复原样有这个设置吗？

**Comment by zhangfeixiang** [comment]
已经删除成功，被补充上来的依然显示左滑后的样式。

**Comment by LJjack** [comment]
添加一个已读按钮，点击按钮后怎么恢复原样,也就是调用LeftScroll的close()

**Comment by LJjack** [comment]
> 点击其他地方。已经左侧滑动自行恢复原样有这个设置吗？

不能

**Comment by caihua** [comment]
_markMap 麻烦改下这个吧

**Comment by caihua** [comment]
经过研究 发现  LeftScrollListItem(
      key:   这个key是关键，需要唯一数字

**Comment by pan365wang** [comment]
添加一个已读按钮，点击按钮后怎么恢复原样,也就是调用LeftScroll的close()

同问，该如何点击后恢复原样，关闭按钮。

**Comment by mjl0602** [comment]
你好，我更新了如下特性，可以轻松操作目标行的状态
### 左滑联动列表（1.3.0）

1. 对于提供同一个`LeftScrollCloseTag`的LeftScroll组件，可以在一个打开时，关闭其他组件
2. 想要关闭特定的行，只需使用以下代码
```dart
// 找到对应tag与key的row状态，改变状态即可
LeftScrollGlobalListener.instance.targetStatus(tag,key) = false;
```

**Comment by kzq5** [comment]
LeftScrollGlobalListener.instance.targetStatus(tag,key).value = false; 应该是这样，少个value

**Comment by mjl0602** [comment]
是的……写错了，不过不妨碍，看一下就能懂的。毕竟编辑器会直接报错。

**Comment by kzq5** [comment]
> 是的……写错了，不过不妨碍，看一下就能懂的。毕竟编辑器会直接报错。

有没有滑动的时候自动恢复的？

**Comment by kzq5** [comment]
> 是的……写错了，不过不妨碍，看一下就能懂的。毕竟编辑器会直接报错。

就是列表上下滑动的时候，被滑动的cell自动恢复

**Comment by mjl0602** [comment]
使用自带的ScrollController监听下滑动，触发方法即可，很简单。

**Comment by kzq5** [comment]
> 使用自带的ScrollController监听下滑动，触发方法即可，很简单。

那我要记录一下那个cell被滑动了是吧

**Comment by mjl0602** [comment]
不用，应该可以使用 LeftScrollGlobalListener.instance.needCloseOtherRowOfTag(yourTag,null)这样关闭

**Comment by kzq5** [comment]
> 不用，应该可以使用 LeftScrollGlobalListener.instance.needCloseOtherRowOfTag(yourTag,null)这样关闭

可以了，谢谢。

**Comment by mjl0602** [comment]
欢迎点个star ;-)
