### ISSUE TITLE
AnimationController为null导致的报错

### ISSUE THREAD

**Issue by jihongboo** [mjl0602/left-scroll-actions#8]
我们的项目会在极端的情况下，同时触发页面pop和cell滑动关闭（CupertinoLeftScrollState.close）
这种情况下，animationController会提早释放，导致animationController.animateTo(0)执行报错。
NoSuchMethodError: The method 'stop' was called on null.

**Comment by mjl0602** [comment]
只是会报个错吧？页面上能明显看到错误显示吗。

**Comment by jihongboo** [comment]
页面上没有错误，影响不是很大

**Comment by mjl0602** [comment]
带动画的Widget多多少少都有这种问题，不影响UI应该没事

**Comment by mjl0602** [comment]
Fixed in 2.3.0 
修复AnimationController使用后未释放的错误，新增LeftScrollController API和LSTag类，更新示例和依赖版本
