### ISSUE TITLE
LeftScrollItem为什么不能添加图片啊

### ISSUE THREAD

**Issue by 1062245999** [mjl0602/left-scroll-actions#9]

**Comment by mjl0602** [comment]
给你留的button类型是Widget，你可以随便加的，LeftScrollItem只是我封装的一个Widget，并没有强制要求是LeftScrollItem。

**Comment by 1062245999** [comment]
哦哦,看到了,不好意思.
顺便在问一个问题,大佬
CupertinoLeftScroll(
              closeTag: LeftScrollCloseTag('a'),
              ...............
),
CupertinoLeftScroll(
              closeTag: LeftScrollCloseTag('a'),
              ...............
),
这种情况下,当我滑动完第一个item时,在去滑动第二个item,第一个item的button会关掉?
(// 当另一个有相同closeTag的组件打开时，其他有着相同closeTag的组件会自动关闭.)我看文档是这么写的,但是我试了一下,好像不行.

**Comment by mjl0602** [comment]
给key了吗，key是必须的

**Comment by 1062245999** [comment]
好了,刚才忘了给key了,感觉!🙏
